### ISSUE TITLE
Hazelcast clustering, when used with sessions is sensitive to what constructors are available in the objects

### ISSUE THREAD

**Issue by apatrida** [vert-x3/vertx-hazelcast#10]
Local storage, for example session store, is tolerant of classes that are deserialized and do not have a default constructor.  Hazelcast when used in clustering with a clustered session store throws exceptions and cannot deserialize the classes that were allowed to be stored into the session.

There needs to be a uniform standard across vertx projects about this because some, like vertx-auth which is obviously going to write to the session does not do so correctly:  https://github.com/vert-x3/vertx-auth/issues/26 (at least for JWT)

And it appears there is no test coverage for each of these session objects that uses cluster session store and hazelcast.  

This should be improved in the project across the board to be consistent and well known what is required of objects that go into session or clustered shared memory.

**Comment by purplefox** [comment]
I'm not sure I understand the issue here.

If you looking for some guidance on what kinds of objects can go into a clustered session of vertx-web?

But in any case, this repo isn't the right place for asking questions about vertx-web, so closing ;)

**Comment by apatrida** [comment]
It was a problem that some other modules, ok, one other module vertx-web was placing items into session that would not work with clustered vertx with hazelcast.  So, having tests use a fake cluster manager that allows some things, but hazel cast cluster manager does not, ... is a problem.

**Comment by apatrida** [comment]
(or if vertx-web JWT auth was never tested with the cluster manager)
