### ISSUE TITLE
broken supporting smart client

### ISSUE THREAD

**Issue by donovankim** [vert-x3/vertx-hazelcast#100]
#90 
it breaks supporting smart client.
all consumers of eventbus and shareddata must be a member of cluster.
is there no other way?

**Comment by tsegismont** [comment]
@donovankim smart client were not supported (e.g see https://github.com/vert-x3/vertx-hazelcast/issues/24).

Unfortunately, the documentation was misleading because it gave the impression smart clients were not supported in HA. Reality was clustered eventbus was not working too.
