### ISSUE TITLE
improvement : HazelcastClusterManager.getDefaultConfig()

### ISSUE THREAD

**Issue by j040p3d20** [vert-x3/vertx-hazelcast#108]
Hi,

this is more a feature request than an issue. It would be very useful to have a static method

HazelcastClusterManager.getDefaultConfig()

so that we can get a default working Hazelcast configuration to customise. Using "new Config()" we get an empty configuration that just wont work ( locks don't work ) . In my company, we frequently need to bind hazelcast to loopback device so that unit tests don't interfere with each other.

**Comment by tsegismont** [comment]
Such a method has been introduced in 3.6: [`loadConfig()`](https://vertx.io/docs/apidocs/io/vertx/spi/cluster/hazelcast/HazelcastClusterManager.html#loadConfig--)
