### ISSUE TITLE
java.lang.ClassNotFoundException: io.vertx.spi.cluster.hazelcast.impl.HazelcastClusterNodeInfo in Apache Karaf

### ISSUE THREAD

**Issue by Ngosti2000** [vert-x3/vertx-hazelcast#111]
vertx-hazelcast requires HazelcastClusterNodeInfo class which is in  io.vertx.spi.cluster.hazelcast.impl package but this package has not been exported hence the error

**Comment by tsegismont** [comment]
@Ngosti2000 can you provide a pull request to fix the OSGI suport?

**Comment by Ngosti2000** [comment]
@tsegismont This solution here sorted me out.
[](https://stackoverflow.com/questions/42528661/vertx-hazelcast-class-serialization-on-osgi-karaf/42531968#42531968)
