### ISSUE TITLE
how impl.MapServiceContextImpl to gc?

### ISSUE THREAD

**Issue by felix-laofan** [vert-x3/vertx-hazelcast#115]
when my jvm run about one or two weeks.many MapServiceContextImpl instance in JVM .how can i gc it.  

One instance of "com.hazelcast.map.impl.MapServiceContextImpl" loaded by "sun.misc.Launcher$AppClassLoader @ 0x740000d50" occupies 990,930,216 (87.93%) bytes. The memory is accumulated in one instance of "java.util.concurrent.ConcurrentHashMap$Node[]" loaded by "<system class loader>".

Keywords
java.util.concurrent.ConcurrentHashMap$Node[]
sun.misc.Launcher$AppClassLoader @ 0x740000d50
com.hazelcast.map.impl.MapServiceContextImpl

**Comment by felix-laofan** [comment]
![image](https://user-images.githubusercontent.com/24423418/60888710-08e62d80-a28a-11e9-834e-5095959ae094.png)

**Comment by felix-laofan** [comment]
my hazelcast config is  this..

**Comment by felix-laofan** [comment]
<?xml version="1.0" encoding="UTF-8"?>



<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.8.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>laofanVertCoolGame</name>
        <password>laofan!@##$$$##</password>
    </group>
    <management-center enabled="false">http://localhost:8080/mancenter</management-center>
    <network>
        <port auto-increment="true" port-count="10">5701</port>
        <outbound-ports>
            
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
            </multicast>
            <tcp-ip enabled="true">
                <interface>127.0.0.1</interface>
                <member-list>
                    <member>127.0.0.1</member>
                </member-list>
            </tcp-ip>
            <aws enabled="false">
                <access-key>my-access-key</access-key>
                <secret-key>my-secret-key</secret-key>
                
                <region>us-west-1</region>
                
                <host-header>ec2.amazonaws.com</host-header>
                
                <security-group-name>hazelcast-sg</security-group-name>
                <tag-key>type</tag-key>
                <tag-value>hz-nodes</tag-value>
            </aws>
            <discovery-strategies>
            </discovery-strategies>
        </join>
        <interfaces enabled="false">
            <interface>10.10.1.*</interface>
        </interfaces>
        <ssl enabled="false"/>
        <socket-interceptor enabled="false"/>
        <symmetric-encryption enabled="false">
            
            <algorithm>PBEWithMD5AndDES</algorithm>
            
            <salt>thesalt</salt>
            
            <password>thepass</password>
            
            <iteration-count>19</iteration-count>
        </symmetric-encryption>
    </network>
    <partition-group enabled="false"/>
    <executor-service name="default">
        <pool-size>2</pool-size>
        
        <queue-capacity>1000</queue-capacity>
    </executor-service>
    <queue name="default">
        
        <max-size>0</max-size>
        
        <backup-count>1</backup-count>

        
        <async-backup-count>0</async-backup-count>

        <empty-queue-ttl>-1</empty-queue-ttl>
    </queue>
    <map name="default">
        
        <in-memory-format>BINARY</in-memory-format>

        
        <backup-count>1</backup-count>
        
        <async-backup-count>0</async-backup-count>
        
        <time-to-live-seconds>0</time-to-live-seconds>
        
        <max-idle-seconds>0</max-idle-seconds>
        
        <eviction-policy>NONE</eviction-policy>
        
        <max-size policy="PER_NODE">0</max-size>
        
        <eviction-percentage>25</eviction-percentage>
        
        <min-eviction-check-millis>100</min-eviction-check-millis>
        
        <merge-policy>com.hazelcast.map.merge.PutIfAbsentMapMergePolicy</merge-policy>

        
        <cache-deserialized-values>INDEX-ONLY</cache-deserialized-values>

    </map>

    <multimap name="default">
        <backup-count>1</backup-count>
        <value-collection-type>SET</value-collection-type>
    </multimap>

    <list name="default">
        <backup-count>1</backup-count>
    </list>

    <set name="default">
        <backup-count>1</backup-count>
    </set>

    <jobtracker name="default">
        <max-thread-size>5</max-thread-size>
        
        <queue-size>0</queue-size>
        <retry-count>0</retry-count>
        <chunk-size>1000</chunk-size>
        <communicate-stats>true</communicate-stats>
        <topology-changed-strategy>CANCEL_RUNNING_OPERATION</topology-changed-strategy>
    </jobtracker>

    <semaphore name="default">
        <initial-permits>0</initial-permits>
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
    </semaphore>

    <reliable-topic name="default">
        <read-batch-size>10</read-batch-size>
        <topic-overload-policy>BLOCK</topic-overload-policy>
        <statistics-enabled>true</statistics-enabled>
    </reliable-topic>

    <ringbuffer name="default">
        <capacity>10000</capacity>
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
        <time-to-live-seconds>0</time-to-live-seconds>
        <in-memory-format>BINARY</in-memory-format>
    </ringbuffer>

    <serialization>
        <portable-version>0</portable-version>
    </serialization>

    <services enable-defaults="true"/>

    <lite-member enabled="false"/>

</hazelcast>

**Comment by felix-laofan** [comment]
[hazelcast-default.zip](https://github.com/vert-x3/vertx-hazelcast/files/3372984/hazelcast-default.zip)

**Comment by felix-laofan** [comment]
how can answer my question?

**Comment by tsegismont** [comment]
The screenshot of the heap analysis does not help to determine which data structures are accumulated. Can you share the dump file or provide relevant details? Thank you.

**Comment by felix-laofan** [comment]
sorry. 19 days ago. dump is delete! i only  use syncMap.   so i change use redis. do not use Hazecast!that my project  is running ok!
