### ISSUE TITLE
Update Hazelcast to 3.12+

### ISSUE THREAD

**Issue by nolequen** [vert-x3/vertx-hazelcast#116]
Some of distributed structures are deprecated (e.g. [ISemaphore](https://docs.hazelcast.org/docs/latest/manual/html-single/#isemaphore) and [IAtomicLong](https://docs.hazelcast.org/docs/latest/manual/html-single/#iatomiclong)) in favor of more reliable ones.
For example, the deprecated implementation of IAtomicLong has only one synchronous backup, and no asynchronous.
Could you please update the dependency to the newest one and use the actual API.

**Comment by vietj** [comment]
@tsegismont can you investigate the version bump of the Hazelcast version ?

**Comment by tsegismont** [comment]
@dhoffer our test suite passes with Hazelcast 3.12.2. If you still have issues, can you provide a simple reproducer on GitHub?
