### ISSUE TITLE
ISemaphore and IAtomicLong deprecated in 3.12.2

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hazelcast#118]
Follows up on #116 

Investigate upgrade options for V4

**Comment by vbekiaris** [comment]
In Hazelcast 4.0 `IAtomicLong` and other deprecated data structures are removed. However CP subsystem introduces an "unsafe" mode with lower consistency guarantees, CP subsystem's atomic long & semaphore could be used instead. See the relevant section of the latest migration guide here: https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#removal-of-deprecated-concurrency-api-implementations
