### ISSUE TITLE
High memory peaks - Hazelcst 3.7.1

### ISSUE THREAD

**Issue by SGjorge** [vert-x3/vertx-hazelcast#127]
Hello everyone,

I’m using Hazelcast cluster into VertX develop, and looking for evidences knowledge about the next performance:
-	When run one microservice (develop unit program), whose connects to hazelcast cluster, I’m see that the other microservices memory use have an increase (around 50Mb per microservice).
Peaks are diferents microservice conections to hazelcast cluster.
 
![memory-peaks](https://user-images.githubusercontent.com/10530660/79978680-93f28600-84a0-11ea-87ff-7cda5cea8418.jpg)

I think it was associated this with:
o	Hz._hzInstance
o	RMI TCP Connection
 
![memory-objects](https://user-images.githubusercontent.com/10530660/79978675-92c15900-84a0-11ea-9f00-e6ec0b01fd34.jpg)

### Error Log when pod memory fail to connect hazelcast.
INFO: [10.126.3.235]:5701 [ClusterKyber] [3.11] 

Members {size:157, ver:8682} [
                Member [10.126.4.185]:5701 - 64c58430-0c56-43a2-8a8c-e40f6d33324b
                Member [10.126.4.123]:5701 - 983d0577-1368-4a52-a78b-89e4e42a0b0e
                Member [10.126.3.199]:5701 - 4f5e4efb-ba7f-4243-98ea-8d60d2764184
                Member [10.126.3.168]:5701 - b96db2de-cfc3-4d70-9893-cbbc11208cb5
                Member [10.126.4.238]:5701 - 865be856-53e8-46cc-a64b-06a92ec1e79c
                Member [10.126.3.123]:5701 - d41d4db6-7562-4bc5-8e87-2e65a9501f54
                Member [10.126.4.247]:5701 - 599855d5-a98a-45f3-b3bc-e2c44eb0fdba
                Member [10.126.3.210]:5701 - de360605-9057-4663-be2d-77500b09e812
                Member [10.126.4.39]:5701 - 648a11c9-7db1-4624-86ca-1f61d3971de4
                Member [10.126.3.177]:5701 - 6adc1f50-1a59-4ccf-9ef7-e901fe0122e7
                Member [10.126.3.150]:5701 - dade8bf6-ae43-4c8c-898f-57235328b954
                Member [10.126.4.60]:5701 - 1868c1e4-1b70-481d-870e-d94a916985c8
                Member [10.126.4.20]:5701 - 7542e29e-b0ac-4e7c-8ace-b22372cc3d8d
                Member [10.126.4.187]:5701 - 3fccc9e5-0571-420b-b30f-8830b65e0cd0
                Member [10.126.3.237]:5701 - 5cf7c956-766c-46b9-b945-75e6915d7cc9
                Member [10.126.4.218]:5701 - 46dee11d-c285-48ca-9327-4fe6e46d377d
                Member [10.126.4.14]:5701 - 830d02b9-6ece-413a-8950-55771b223b9c
                Member [10.126.4.190]:5701 - d56145f5-3b72-40ae-b1b1-bdd5ede59256
                Member [10.126.4.37]:5701 - 10aefe91-1e19-4c8b-bdac-ac7e1fc1f507
                Member [10.126.3.181]:5701 - c8f97519-ad07-4cab-83bb-df705a97a82b
                Member [10.126.4.34]:5701 - 1f942087-df4a-43fb-a9c3-3812e07500b7
                Member [10.126.3.243]:5701 - 924dba3b-36d6-41d4-9a08-e3bdb4b4c3f3
                Member [10.126.4.211]:5701 - 543e0a3c-adc3-4245-b503-d81e74117752
                Member [10.126.3.254]:5701 - 1ea9fbeb-453e-419b-8dc8-4acc8a9af5a9
                Member [10.126.4.50]:5701 - eb3efb06-5bbd-4203-afc4-3be47527eaa2
                Member [10.126.3.178]:5701 - 5bfc2ea0-454a-4c57-ae02-54baa24dcca7
                Member [10.126.3.135]:5701 - 534f01b6-bbce-4b7e-abca-addfc2ff34ec
                Member [10.126.3.226]:5701 - f0aa07d0-dd41-4300-9b87-bb24442e0f7a
                Member [10.126.4.47]:5701 - 841c0ba2-b12d-4c04-92fb-6592fa6cd53a
                Member [10.126.3.255]:5701 - 57c1ce3d-60d8-4421-ad20-a8584ccef017
                Member [10.126.3.245]:5701 - 424a689d-f459-470f-acc2-9edab40da423
                Member [10.126.4.236]:5701 - b4051b1a-ddc1-46c5-ba5a-bbebb0e3fba9
                Member [10.126.4.234]:5701 - 15e92a2b-1416-4df1-bc84-96a9bbd96995
                Member [10.126.3.190]:5701 - 2f887c31-ed12-4426-a352-6dbe2ab27f78
                Member [10.126.4.55]:5701 - 0702dcd8-d1f6-4882-898c-96c8d57536f8
                Member [10.126.3.151]:5701 - ac57a903-170a-4719-8361-6f237914faab
                Member [10.126.4.243]:5701 - 2b149973-6732-4a8d-9204-1ecf15fed0c2
                Member [10.126.3.122]:5701 - 36e63c77-e9e1-4b27-a3b9-a73cbf5e7b65
                Member [10.126.4.227]:5701 - 36e01eb6-19dc-4bc3-bd86-1335c22c42b0
                Member [10.126.4.22]:5701 - 586fb361-9ec0-4a52-8d9a-b1e930e53969
                Member [10.126.4.119]:5701 - 7e0a11cd-e7f0-4df3-8af1-a6c0ada756d6
                Member [10.126.4.121]:5701 - eb804d8f-8fde-479b-895e-ffe40969cedf
                Member [10.126.3.125]:5701 - 5c54a17e-0998-42a7-8403-024497590916
                Member [10.126.3.144]:5701 - 24c56262-e3cd-44ef-8fca-da5f601b6c0b
                Member [10.126.3.167]:5701 - 171c685f-6b69-4cf4-a136-07860acd2d79
                Member [10.126.3.157]:5701 - 0536cba4-739f-434d-a837-4a56a602e5cb
                Member [10.126.4.209]:5701 - 530a1dc8-246a-4412-98c3-b4f307282c3e
                Member [10.126.3.160]:5701 - 92b2a414-f4ac-4d8c-b46b-de18954113d9
                Member [10.126.4.0]:5701 - 4345211c-f496-4955-9e46-3f1c95b7bec8
                Member [10.126.3.134]:5701 - bdd772e0-43f5-422b-8e7c-71973d6ac5a0
                Member [10.126.3.221]:5701 - d3595439-e997-4d82-9575-dee2ecaf064e
                Member [10.126.4.21]:5701 - 7bcfff4f-aec5-4faf-ac81-7f4ad882c457
                Member [10.126.4.23]:5701 - b981e39f-e538-4a7e-8596-b803774074fc
                Member [10.126.3.156]:5701 - 4c70fe92-307e-4c82-bbb2-68f6e0a82e4f
                Member [10.126.3.200]:5701 - 8060848d-a6c2-462f-b62a-7f50c1833ed8
                Member [10.126.3.207]:5701 - e81a90b7-a6f2-4bb2-ab33-a9898a791962
                Member [10.126.3.249]:5701 - 0f5a31c8-bc35-4cd1-abb1-55575fd42794
                Member [10.126.3.244]:5701 - 554a8eab-199a-4c96-b7fe-b215e48865b4
                Member [10.126.3.202]:5701 - 7be6f1e6-af66-4a06-9709-d9ff5058e6d4
                Member [10.126.4.242]:5701 - 4a2d3040-dbc6-418b-9181-41890379cfa8
                Member [10.126.4.11]:5701 - f94b6b45-4062-4029-a13f-4ac90fa64571
                Member [10.126.4.45]:5701 - 5d56d2f6-137a-4d43-9128-0ceedaf93e87
                Member [10.126.3.215]:5701 - b168c88b-324e-4c74-a8d6-9ca028777872
                Member [10.126.3.139]:5701 - 29bd0614-c6b9-4e56-9985-11dad3fb7ab9
                Member [10.126.3.213]:5701 - b59ac984-be86-4744-85cd-1c3cd5e74c4e
                Member [10.126.4.249]:5701 - c6ca00c6-fa0e-4feb-b44e-1493a37f8405
                Member [10.126.3.141]:5701 - 9c127614-de09-4499-b2a6-f37420bcea5d
                Member [10.126.3.163]:5701 - 3eb908b7-68be-4a35-8eb7-026c3b24023f
                Member [10.126.3.184]:5701 - 7edc0077-536d-4058-89e5-083c4c18f728
                Member [10.126.4.10]:5701 - 9e62bc04-a6ec-4c8e-b6fa-4dbbef42f5c0
                Member [10.126.2.120]:5701 - 8f9a653f-c979-4a7a-82ab-b03662f20b6a
                Member [10.126.2.143]:5701 - e26037f3-90a2-423f-810e-dd08d7056fdd
                Member [10.126.2.122]:5701 - cbb475a7-f8d1-40f8-8240-77951c4c6f35
                Member [10.126.2.137]:5701 - d07734bf-4457-43fe-87d2-a93e1db160a9
                Member [10.126.3.192]:5701 - cfa0fc19-169d-4668-942f-743dcfae9408
                Member [10.126.3.235]:5701 - 48a690fd-b87c-4fc0-8127-c8032b28098a this
                Member [10.126.4.196]:5701 - 4d189ec8-e085-4379-a051-5dec59d2133a
                Member [10.126.3.233]:5701 - 7667e68a-fc2d-434b-9eaa-bd080b543c28
                Member [10.126.3.234]:5701 - 38d10723-b971-4e18-9231-d66e5197f4e7
                Member [10.126.4.124]:5701 - eb0087a3-ae30-4ab7-b245-f2eb576bfc25
                Member [10.126.3.127]:5701 - 1ffbaaa6-50c7-405c-be60-4d5e496d692b
                Member [10.126.4.203]:5701 - 94afd6c4-29d9-4400-b745-b9208d139064
                Member [10.126.4.244]:5701 - da02ee0a-839c-4c77-85e4-3f0c128ba9d8
                Member [10.126.2.147]:5701 - bee9f84e-37e4-41f2-9c43-5e180fb3b248
                Member [10.126.4.229]:5701 - 8b2e9077-343b-472e-8b12-9aac707a234c
                Member [10.126.3.248]:5701 - fa25a884-a95c-4b5f-83f9-8a033811f873
                Member [10.126.3.229]:5701 - a1abb8a5-b4d1-40ad-a1f2-f90085091506
                Member [10.126.3.225]:5701 - b98afbfd-413c-4903-aeb0-2914d0169042
                Member [10.126.3.250]:5701 - 600b515e-d378-4313-b21f-f6165c5c952e
                Member [10.126.4.213]:5701 - 55f075ab-bc40-4550-a897-74248e762e62
                Member [10.126.4.25]:5701 - a64cbdfb-90ed-4877-b7ea-411174af5b73
                Member [10.126.4.61]:5701 - 8ef89eb3-a2f6-4a60-928d-59e509852c9f
                Member [10.126.4.9]:5701 - 6c98773b-9ca6-4caf-acfb-04286df52594
                Member [10.126.4.31]:5701 - e5de621f-ea02-42d6-adbd-65bf93010b2a
                Member [10.126.4.24]:5701 - 464ccfde-2ac7-485c-8cd9-5caa6884dd2e
                Member [10.126.4.222]:5701 - 96a7d248-5c93-4038-8112-d3e9ee15cc50
                Member [10.126.3.166]:5701 - bccbaef0-52ff-4b89-a793-f5c45b51fdb8
                Member [10.126.4.245]:5701 - 977113d0-6fec-4a28-8dcf-25d73b43b052
                Member [10.126.3.153]:5701 - 174aae9c-8ff4-4f56-b04a-72df1451fae8
                Member [10.126.3.194]:5701 - 27cf2d0b-2a44-41dd-8de2-9878abf8a6e7
                Member [10.126.4.62]:5701 - 798a2aae-1863-463c-abb7-52d434982125
                Member [10.126.3.146]:5701 - 3836545d-db23-482b-acbb-81d172052c82
                Member [10.126.4.219]:5701 - 48c05491-a6af-4782-ae4c-3cd21bfd993f
                Member [10.126.2.116]:5701 - 2617291a-5a12-47e2-ae7e-ff4915fb8113
                Member [10.126.2.145]:5701 - 4d74cbae-ff0d-4b8b-a930-024675b5a649
                Member [10.126.2.144]:5701 - d7b0d391-5ac7-4d3b-a398-3e7ec914134b
                Member [10.126.3.208]:5701 - d43d2571-622a-4a6e-a557-3d1cd3962e10
                Member [10.126.3.201]:5701 - 4d28c3c2-b926-4310-81c4-6a4f24c3bc47
                Member [10.126.4.220]:5701 - b0dc826f-b3e7-41f4-b82f-48032659b405
                Member [10.126.4.51]:5701 - 2f9fc2f6-76f8-4b40-bdc3-383017df3b31
                Member [10.126.3.169]:5701 - 178cc0f6-4a8d-49c5-aa6a-966ef09d58be
                Member [10.126.4.53]:5701 - 26e1190d-8052-46c6-a752-e6cf4794d45e
                Member [10.126.4.191]:5701 - 4525436e-01eb-42c1-af24-040df7aca304
                Member [10.126.3.222]:5701 - fbc8306b-e561-4eda-9456-92a1622a2ccc
                Member [10.126.4.2]:5701 - 336ea2fe-8a56-43b8-b2a8-d4d7ae15cc38
                Member [10.126.3.136]:5701 - b51ec027-25c2-4b37-8476-b5e560d615d2
                Member [10.126.4.16]:5701 - 6403ee42-4573-4945-ac10-79a5629db897
                Member [10.126.3.219]:5701 - 4349479a-2336-48e4-a69a-dd5e5ff389a0
                Member [10.126.2.119]:5701 - 8d65db06-01d5-433b-ae0d-30cae80671d9
                Member [10.126.3.171]:5701 - 54e2df2a-74e6-47be-8221-f29e3b737d52
                Member [10.126.3.164]:5701 - b475ac4e-110b-4ae8-8ad2-ea64d34409bc
                Member [10.126.3.158]:5701 - e70b287f-349d-4619-90a1-6bacebe431d3
                Member [10.126.2.139]:5701 - d5081c71-4591-4c7f-b0dd-073c28a9e1d8
                Member [10.126.3.142]:5701 - b76e8505-2f4d-441b-b7e1-30c14ee3d10b
                Member [10.126.3.170]:5701 - 8f874ebc-f533-48e9-92fb-0f55c76f71bf
                Member [10.126.2.110]:5701 - 306b8e3c-3f00-4858-8a57-e6d548675ef2
                Member [10.126.4.216]:5701 - 7d048822-ef59-4511-866c-531c935d2df8
                Member [10.126.4.120]:5701 - 4b657a18-fec6-4399-bfee-4ef12b9a7139
                Member [10.126.3.124]:5701 - 981536cb-9138-480a-b51e-118bc0cc1329
                Member [10.126.4.214]:5701 - adced079-6a39-4e4a-90ae-4053181c8ee2
                Member [10.126.4.207]:5701 - 0832193a-342e-4bd8-b087-33a774ad9b5d
                Member [10.126.4.57]:5701 - 6960d2cb-6acd-4552-a44e-1efc58aa7937
                Member [10.126.4.199]:5701 - 74b0293a-e148-4b4c-92f3-f46a9fa56fc2
                Member [10.126.4.235]:5701 - 2c0b9214-755c-471d-b8dd-c0c8d379e85f
                Member [10.126.3.129]:5701 - e39211a9-b26c-44a4-9942-eff4202a3471
                Member [10.126.4.223]:5701 - ca3ec9af-e9ea-40b1-9e3a-e11f7b0376e1
                Member [10.126.3.236]:5701 - 5a0ecd73-66b6-4623-aa45-f81771006748
                Member [10.126.2.148]:5701 - 06e57df1-5600-47cd-bdd0-2fbf53d6e655
                Member [10.126.3.197]:5701 - 03034b47-adca-4921-b641-1a02bcb09a25
                Member [10.126.3.196]:5701 - e46fa746-e5c3-48aa-9345-ec893b8550e8
                Member [10.126.4.233]:5701 - 7249866f-f4a3-423b-9eaf-c2d410624b8f
                Member [10.126.3.126]:5701 - eee1d15c-3270-444d-ba87-ab869cd86266
                Member [10.126.3.189]:5701 - 3c26a116-ca5c-4a08-80e0-0ec7a6741ec6
                Member [10.126.4.230]:5701 - 6ff39561-517f-4761-b8a6-0cec9bf38bd2
                Member [10.126.3.238]:5701 - a09d9612-5cea-4233-b59f-3c193de17bbe
                Member [10.126.3.223]:5701 - 11962235-a8d2-4711-affc-3dc40957e321
                Member [10.126.2.109]:5701 - 1b523755-58ea-4d9b-bd87-d4aed46c8f79
                Member [10.126.3.193]:5701 - 52fb06f9-9bdc-48ed-bfb8-9d83e6f0dde9
                Member [10.126.4.36]:5701 - 2e13e4ee-0c2b-4f6a-9fbe-3be7f80a2c76
                Member [10.126.2.108]:5701 - 2aef3347-3984-43ab-b430-ccb0fc52a4cb
                Member [10.126.1.65]:5701 - 2c528e5b-fd43-456a-89fe-dba64e307a0c
                Member [10.126.1.76]:5701 - 5a852dc9-b1de-437d-8e45-2324041c4861
                Member [10.126.3.217]:5701 - f1440099-0e40-4487-bfa3-38ef3ee5a194
                Member [10.126.4.202]:5701 - 417d9463-cd07-4333-a530-b982b5cda111
                Member [10.126.1.66]:5701 - ae7ecb75-5cf4-4ad4-8ca2-07b94798b61a
                Member [10.126.3.179]:5701 - b33ef10f-7871-4ef1-a538-f7ce55abec4d
                Member [10.126.1.77]:5701 - 35122a13-fdc9-407f-bf39-95990c119f5d
]

Apr 21, 2020 5:47:38 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [10.126.3.235]:5701 [Cluster] [3.11] Could not connect to: /10.126.1.64:5701. Reason: SocketException[Connection refused to address /10.126.1.64:5701]
Apr 21, 2020 5:47:38 PM com.hazelcast.nio.tcp.TcpIpConnectionErrorHandler
WARNING: [10.126.3.235]:5701 [Cluster] [3.11] Removing connection to endpoint [10.126.1.64]:5701 Cause => java.net.SocketException {Connection refused to address /10.126.1.64:5701}, Error-Count: 5
Apr 21, 2020 5:47:42 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.126.3.235]:5701 [Cluster] [3.11] Connection[id=966, /10.126.3.235:5701->/10.126.1.77:51463, endpoint=[10.126.1.77]:5701, alive=false, type=MEMBER] closed. Reason: Connection closed by the other side
java.io.EOFException: Remote socket closed!
                at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116)
                at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368)
                at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353)
                at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:279)
                at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:234)
 
### Question:
               I would like to know more about this, because I’m having some memory problem when running into AKS (average memory estimated in 7,5GB – 50Mb per pod * 150 pod/microservices ).
               Cluster.xml in use:
             
 [cluster.xml.txt](https://github.com/vert-x3/vertx-hazelcast/files/4515917/cluster.xml.txt)

**Comment by tsegismont** [comment]
Conversation on https://groups.google.com/d/msg/vertx/wpMLMsMXWqc/IoR3MSb0AQAJ
