### ISSUE TITLE
We should use consistent naming prefix for internal maps

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-hazelcast#14]
https://github.com/vert-x3/vertx-hazelcast/blob/master/src/main/resources/default-cluster.xml#L77

As discussed.

**Comment by vietj** [comment]
+1

**Comment by purplefox** [comment]
BTW, was there a resolution on that clustering issue you were looking into before the 3.1 release?

**Comment by tsegismont** [comment]
It seems to me that all internal maps use the `__vertx.` prefix in master.
