### ISSUE TITLE
ClusteredEventBus is not removing connection when Hazelcast member leaves the cluster

### ISSUE THREAD

**Issue by MikiLoz92** [vert-x3/vertx-hazelcast#141]
### Version

4.0.3

### Context

It appears that, under Vert.x 4, a member will **not** be removed from the `connections` hashmap under `ClusteredEventBusImpl`, and its `ConnectionHolder` will **not** be closed whenever a member leaves the Hazelcast cluster.

On a clustered EventBus setup, this makes Vert.x think that the previous member (which has already left) is available to make a connection on the EventBus port (in our case 15701).

```
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492690860Z [WARN ] 2021-03-19 13:14:19.489 [vert.x-eventloop-thread-2] PartitionServiceProxy: 67 - [172.17.1.16]:5701 [dev] [4.0.3] Error while querying cluster's safe state
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492761260Z com.hazelcast.core.MemberLeftException: Member [172.17.6.15]:5701 - 54207d1d-5323-44cf-98d4-573f968e2aa7 lite has left cluster!
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492771523Z       at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.onTargetLoss(InvocationMonitor.java:429)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492779543Z       at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.run0(InvocationMonitor.java:396)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492787478Z       at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorTask.run(InvocationMonitor.java:255)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492795396Z       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492802769Z       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492810080Z       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492818166Z       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492826331Z       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492834324Z       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:19.492842071Z       at java.lang.Thread.run(Thread.java:748)
```
And some seconds later, when we send a message through the EventBus...
```
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:25.529967030Z [INFO ] 2021-03-19 13:14:25.529 [hz.elated_grothendieck.cached.thread-5] TcpIpConnector: 65 - [172.17.1.16]:5701 [dev] [4.0.3] Could not connect to: /172.17.6.15:5701. Reason: SocketException[Host is unreachable to address /172.17.6.15:5701]
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:25.539395708Z [WARN ] 2021-03-19 13:14:25.539 [hz.elated_grothendieck.cached.thread-5] TcpIpConnectionErrorHandler: 67 - [172.17.1.16]:5701 [dev] [4.0.3] Removing connection to endpoint [172.17.6.15]:5701 Cause => java.net.SocketException {Host is unreachable to address /172.17.6.15:5701}, Error-Count: 6
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419425451Z [WARN ] 2021-03-19 13:14:26.418 [vert.x-eventloop-thread-4] ConnectionHolder:  - Connecting to server 86d47754-6872-4227-81d8-b99f7ccbc4ca failed
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419468524Z io.netty.channel.AbstractChannel$AnnotatedConnectException: Operation timed out: /172.17.6.15:15701
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419476330Z Caused by: java.net.ConnectException: Operation timed out
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419482367Z       at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419488436Z       at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419494210Z       at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419500615Z       at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419507306Z       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419513333Z       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419519394Z       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419525316Z       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419531285Z       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419537499Z       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419543282Z       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
vehicles-85ffb489fd-qdjcp vehicles 2021-03-19T13:14:26.419549394Z       at java.lang.Thread.run(Thread.java:748)
```

as can be seen above, Vert.x is trying to send the message to the member that has already left.

This is happening under our Kubernetes setup whenever we perform a pods rollout. The pods will be deleted and recreated but it appears that the list that keeps Vert.x under the Hazelcast Cluster is not getting updated as old members are removed.

The result is that, if we deploy a Hazelcast data nodes cluster from scratch (replicaset of 3 data nodes) and then deploy our app (another replicaset of 3 instances of our app, all lite members), everything works fine.

However, when we perform a rollout of our app, the new pods will start trying to communicate with the older pods through the EventBus using the old pods' IPs, and this behavior persists in time.

**Comment by tsegismont** [comment]
Can you please share a small reproducer? I am particularly interested in
the rollout setup.

**Comment by tsegismont** [comment]
Also, do you observe a similar behavior when adding/removing pods with the
same version?

Thank you

Le ven. 19 mars 2021 à 16:10, Thomas SEGISMONT ***@***.***> a
écrit :

> Can you please share a small reproducer? I am particularly interested in
> the rollout setup.
>
> Le ven. 19 mars 2021 à 15:04, Miguel Vera Belmonte <

**Comment by MikiLoz92** [comment]
HI @tsegismont, after reviewing the issue this weekend and trying to come up with a basic reproducer, I have not succeeded so far. To answer your question, it does happen when we remove any pod in our deployment.

It seems that the issue lies in some custom code that we have in place, that provides consumer-group-like functionality (similar to the one in [this GH issue](https://github.com/eclipse-vertx/vert.x/issues/2432)). However, it was working flawlessly in Vert.x 3, so it makes us consider whether something has changed in the way clustered consumers are handled in Vert.x 4. In particular whether sending a message to an address that was owned by some member if that member is already deregistered (and no one else owns that address), which seems to be what's causing the exception. In Vert.x 3 this didn't fail, but now it is failing. Would you happen to know if this behavior has been changed?

I'll keep investigating this week and come up with more insights, or close the issue if I can't.

**Comment by tsegismont** [comment]
Hi, Vert.x 4 changed the clustering SPI and thus the storage of eventbus
subscriptions.
You can learn the rationale behind this change in
https://github.com/vert-x3/wiki/wiki/RFC:-clustering-SPI-revisited

**Comment by MikiLoz92** [comment]
I see, thanks for the insights @tsegismont 😄. I was able to rewrite our code taking into account the new subscription storage model. Closing this since not a bug.

**Comment by tsegismont** [comment]
Thanks for letting us know
