### ISSUE TITLE
Hazelcast version upgrade

### ISSUE THREAD

**Issue by pskarthic** [vert-x3/vertx-hazelcast#147]
Currently vertx is using hazelcast version 4.0.2, this version is being marked as vulnerable. I can see the current snapshot is using 4.1.2 hazelcast, when this snapshot will be upgraded to release version. 
Until the release version is ready, can I upgraded hazelcast alone, currently I am using 4.0.2 vertx version and I can try upgrading to 4.1.2 if necessary.

**Comment by tsegismont** [comment]
Duplicates #145
