### ISSUE TITLE
Project dependency hazelcast-all

### ISSUE THREAD

**Issue by vh1572** [vert-x3/vertx-hazelcast#148]
Hi,

Would it be possible to use dependency hazelcast-all.jar instead of hazelcast.jar?

The reason behind this request is that I'm working on a project using ES4X (graalvm + es4x + vertx) having vertx in a clustered mode using hazelcast. The setup works locally but cannot be deployed under kubernetes, because there are missing some classes, which are available either in a separate jar (hazelcast-kubernetes), or they are also available in hazelcast-all.

It is generally not possible to deploy "extra" jars with es4x. The @vertx/hazelcast npm package is fully relying on the vertx-hazelcast.

I think there are no major disadvantages, the library size is slightly bigger.

Thanks,
Csaba Vajda

**Comment by tsegismont** [comment]
I prefer not forcing a uber-jar dependency on the community, many if not most users don't need it.

It is quite straightforward to [add a JAR dependency to an ES4X project](https://reactiverse.io/es4x/advanced/jars.html).

**Comment by vh1572** [comment]
Ok, indeed, found the way to include the missing jar.

Thanks
