### ISSUE TITLE
Upgrade to Hazelcast Platform 5.x

### ISSUE THREAD

**Issue by contrebande-labs** [vert-x3/vertx-hazelcast#155]
#### Describe the feature

Upgrade to Hazelcast Platform >= 5.2.x if only for the [async `MapLoader`](https://github.com/hazelcast/hazelcast/issues/14483).

#### Use cases

There are no new features being added to Hazelcast IMDG. So any use case relying on the new features (such as async `MapLoader`s), really.

#### Contribution

I'm willing to look into it to see if [a simple maven dependency version bump is all it takes as suggested here](https://docs.hazelcast.com/hazelcast/latest/migrate/upgrading-from-imdg-4), if it has not been done already.

**Comment by tsegismont** [comment]
Fixed by https://github.com/vert-x3/vertx-hazelcast/pull/184
