### ISSUE TITLE
Target of invocationhazelcast cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.

### ISSUE THREAD

**Issue by 1ssqq1lxr** [vert-x3/vertx-hazelcast#158]
### Questions
We build an mqtt cluster based on vertex, when using the MQTT protocol, the cluster manager has no problems, but when starting MQTTS, the following errors will be reported for a period of time (not fixed):
Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.
### Version
vertx-core：<version>4.2.6</version>
hazelcast：4.2.2
Which version(s) did you encounter this bug ?

### Context

         Config config = new Config();
                                config.setClusterName(clusterConfig.getClusterName());
                                Optional.ofNullable(network.getTcpIp())
                                            .ifPresent(tcpIpConfig ->
                                                        config.getNetworkConfig()
                                                                    .getJoin()
                                                                    .getTcpIpConfig()
                                                                    .setEnabled(true)
                                                                    .setMembers(tcpIpConfig.getMembers()));
                                Optional.ofNullable(network.getMultiCast())
                                            .ifPresent(multiCastConfig ->
                                                        config.getNetworkConfig()
                                                                    .getJoin()
                                                                    .getMulticastConfig()
                                                                    .setMulticastPort(multiCastConfig.getPort())
                                                                    .setMulticastGroup(multiCastConfig.getMulticastGroup())
                                                                    .setEnabled(true));
                                config.getCPSubsystemConfig().setCPMemberCount(clusterConfig.getNetwork().getCpCount());
                                config.setLiteMember(false);
                                config.getManagementCenterConfig().setTrustedInterfaces(
                                            Optional.ofNullable(clusterConfig.getNetwork().getTrustedIps()).orElseGet(()->{
                                                Set<String> ips = new HashSet<>();
                                                ips.add("localhost");
                                                ips.add("127.0.0.1");
                                                return ips;
                                            })).setScriptingEnabled(true);
                                return new HazelcastClusterManager(config);

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra
jdk 8.13B

**Comment by tsegismont** [comment]
Can you provide more info? What is changed in the config / dependencies if you enable MQTTS?

I fail to see how this could impact Hazelcast CM.

**Comment by 1ssqq1lxr** [comment]
WARNING: [127.0.0.1]:5701 [base_old] [4.2.5] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.metrics.managementcenter.ReadMetricsOperation{serviceName='hz:impl:metricsService', identityHash=1479810253, partitionId=-1, replicaIndex=0, callId=-1682996, invocationTime=1659811293705 (2022-08-07 02:41:33.705), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1659811293705, firstInvocationTime='2022-08-07 02:41:33.705', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 08:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: ExceptionalResult{cause=com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5701 - 361c4d32-1267-479f-a45a-3511f0a9dcaa this has left cluster!}, offered value: com.hazelcast.internal.metrics.managementcenter.ConcurrentArrayRingbuffer$RingbufferSlice@56f3f9bb
java.lang.Exception
        at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1219)

**Comment by 1ssqq1lxr** [comment]
"network": {
      "tcpIp": {
        "members": [
          "127.0.0.1"
        ]
      },
      "trustedIps":["192.168.8.57"]
    },

**Comment by 1ssqq1lxr** [comment]
When a single node starts a cluster, this exception will be thrown after running for a period of time, and then the cluster function will fail

**Comment by 1ssqq1lxr** [comment]
"network": {
      "tcpIp": {
        "members": [
          "127.0.0.1"
        ]
      },
      "trustedIps":["192.168.8.57"]
    },

**Comment by tsegismont** [comment]
Unable to reproduce
