### ISSUE TITLE
vertx-hazelcast 4.4.x is not able to unregister member from previous version if they are not cleanly stopped.

### ISSUE THREAD

**Issue by lcharlois-neotys** [vert-x3/vertx-hazelcast#181]
Hello,

From what I can see the fix for #174  (PR #175 ) is not present in the code released under versions 4.4.2, 4.4.3 and 4.4.4.
I just discovered, releases 4.4.2, 4.4.3 and 4.4.4 has been done on branch 4.x and not 4.4.

The release note is mentioning the fix [to has been released](https://github.com/vert-x3/wiki/wiki/4.4.2-Release-Notes#vertx-hazelcast), however it's wrong.

Best,

**Comment by lcharlois-neotys** [comment]
A PR (#182 ) to apply the fix from branch 4.4 to 4.x has been open.

**Comment by tsegismont** [comment]
Fixed by #182

**Comment by lcharlois-neotys** [comment]
@tsegismont Do you have an ETA for a 4.4.5 release ?

**Comment by lcharlois-neotys** [comment]
Hello @tsegismont ,

I see that Netty 4.1.96.FInal has been released on July 27th.
Do you have an ETA for a 4.4.5 release of vertx?

**Comment by tsegismont** [comment]
Hi @lcharlois-neotys 

The current plan is to release by the end of this week.
