### ISSUE TITLE
Bump hazelcast version to 3.6

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-hazelcast#21]
HZ 3.6 was just released, we should update.
This is for 3.3.0 and not 3.2.1. 

The pom can be cleaned up as the new HZ 3.6 pom does not import transitive dependencies anymore.

**Comment by plombardi89** [comment]
How will this effect upgrading Vert.x clusters using 3.5.2? Currently Hazelcast does not support any kind of rolling upgrade and 3.5.2 nodes will not be able to talk to 3.6 per this issue: https://github.com/hazelcast/hazelcast/issues/14

**Comment by cescoffier** [comment]
Gonna be 3.6.1.

**Comment by cescoffier** [comment]
@plombardi89 yes it's not compatible protocol wise, however the documentation will be updated to tell you how you can still use 3.5.2. We are going to test against 3.5.2 and 3.6.1
