### ISSUE TITLE
System property -Dhazelcast.config not supported

### ISSUE THREAD

**Issue by estebanlll** [vert-x3/vertx-hazelcast#22]
Would be great to have support for this property when an embedded is used, otherwise is impossible to have differents hazelcast cluster config per environment.

**Comment by purplefox** [comment]
You can specify different hazelcast configs for different environments just by adding the config (called cluster.xml) on the classpath.

**Comment by estebanlll** [comment]
Are you sure? if I execute **java -jar something-fat.jar -cluster** the option -cp doesn't work, and the cluster.xml is inside of the fat jar.

**Comment by purplefox** [comment]
Do you have an example project that demonstrates the issue? There are many ways to build an application with Vert.x so it's hard to diagnose this without further information.

**Comment by estebanlll** [comment]
My bad, I was trying to do **java -jar something-fat.jar -cluster -cp cluster.xml**. Pointing directly to the xml, but I move it inside of a conf directory and then **java -jar something-fat.jar -cluster -cp conf** works.
