### ISSUE TITLE
Documentation should indicate that default JDK needs to be overridden in custom cluster.xml

### ISSUE THREAD

**Issue by dan-lind** [vert-x3/vertx-hazelcast#27]
The default cluster.xml contains 
```
<properties> 
   <property name="hazelcast.logging.type">jdk</property> 
</properties>
```

This means that even if you add something something like this to the command line
`-Dhazelcast.logging.type=slf4j`
the default JDK logging will take priority.

This should be highlighed in the documentation.

Please see the following discussion
https://groups.google.com/forum/#!topic/vertx/PiOviVwwcM0

**Comment by dan-lind** [comment]
From what I have observed, only setting 
`-Dhazelcast.logging.type=slf4j` 
would not be enough. As you @cescoffier mentioned in the above referenced discussion , the default-cluster.xml includes the following properties
```
<properties>
    <property name="hazelcast.mancenter.enabled">false</property>
    <property name="hazelcast.memcache.enabled">false</property>
    <property name="hazelcast.rest.enabled">false</property>
    <property name="hazelcast.wait.seconds.before.join">0</property>
    <property name="hazelcast.logging.type">jdk</property>
  </properties>
```

It looks to me like this takes precedence over whatever you put in Dhazelcast.logging.type.
I think this is still not clear in the updated documentation.

**Comment by cescoffier** [comment]
Are you sure it takes precedence ?

So in that case the only way to override it is to come with your own cluster.xml

**Comment by cescoffier** [comment]
Actually, we can simply drop the line in the default-cluster. It uses jdk anyway by default.

**Comment by dan-lind** [comment]
I actually had this issue a while ago where I passed
`-Dhazelcast.logging.type=slf4j`
and could not understand why it had no effect.

I had my own cluster.xml (copy paste from defaul-cluster.xml) and set my own interfaces etc, but did not realize that the 
`<property name="hazelcast.logging.type">jdk</property>`
was there. When I removed it it finally got the hazelcast logs to slf4j. 

Dropping the line from default-cluster sounds good.

**Comment by cescoffier** [comment]
@dan-lind  - I've removed the explicit setting to jdk in the `default-cluster.xml`. Could you test it ?

**Comment by dan-lind** [comment]
Tried pulling the 3.3.0-SNAPSHOT, but it's still there. Looks like the build of vertx-hazelcast is failing?

**Comment by cescoffier** [comment]
Just deployed a version manually. So, should be there. You need to configure your pom to retrieve artifacts from the OSS Snapshot repository.

**Comment by dan-lind** [comment]
Verified, it's working. When setting -Dhazelcast.logging.type=slf4j if will log to slf4j, and if I don't specify anything it will fallback to jsk like you already said.

**Comment by cescoffier** [comment]
Thanks @dan-lind ! This one can be closed.
