### ISSUE TITLE
HazelcastAsyncMap should not rely on executeBlocking()

### ISSUE THREAD

**Issue by jerrinot** [vert-x3/vertx-hazelcast#28]
Current implementation of `HazelcastAsyncMap` uses `executeBlocking()` for all its method. 

I wrote a small prototype showing how to hook into Hazelcast `ICompletableFuture`. See: https://github.com/jerrinot/vertx-hazelcast/commit/26374717c4d77c57768c03a8fc417fa82d86c1a4

This way you do not consume a thread per each in-flight operations. The prototype relies on casting into `ICompletableFuture`, however this is very unlikely to change in future versions of Hazelcast and if there is a change then it will be caught be tests anyway. 

Would you accept a Pull Request with a changeset similar to the one I linked? 

Any kind of feedback is welcome!

**Comment by cescoffier** [comment]
That would be great.

I'm worried about loosing the compatibility with version of Hazelcast not having this async API. I can't remember when they added it. If it was added after 3.4, definitely a go. 

So, I would love having a PR with such a feature !

**Comment by jerrinot** [comment]
@cescoffier: that's great to hear! I am actually from Hazelcast and we are not going to break this  anytime soon:) We are planning to refine the contract of async methods to return `ICompletableFuture` instead of a regular `Future`. We just need to do it in a way which will not break binary compatibility. 

Any advice how to prevent excessive creation of `VertxExecutorAdapter` ? Is it possible to store it inside vert.x `Context`?

**Comment by purplefox** [comment]
This is great, but I am concerned that we will be relying on a hidden API that has no guarantee of forward or backward compatibility.

I suggest for now we keep the old integration using executeBlocking, and allow usage of the private API as an option. When Hazelcast make the async API public and provide compatibility guarantees for it we can get rid of the old integration.

**Comment by jerrinot** [comment]
@purplefox: thanks for feedback! 
what's the best way to add the switch? Would a new implementation of `AsyncMap`  make sense to you?

**Comment by purplefox** [comment]
Two implementations of AsyncMap sound reasonable, but I'll defer to the core team on this for their decision, as I'm just a guy in the community these days :)

**Comment by cescoffier** [comment]
I think having 2 implementation and a switch to pass from one to the other one would be a reasonable approach.

**Comment by vietj** [comment]
:+1:

**Comment by cescoffier** [comment]
PR merged.
