### ISSUE TITLE
Add support for Hazelcast configuration using system property

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/vertx-hazelcast#36]
As discussed [here](https://groups.google.com/forum/#!topic/vertx/WSa6NDmdXjw) the `-Dhazelcast.config` system property is **not** supported by Vert.x and this PR adds a note about this: #35 
But currently the code uses an opinionated way of providing config: Putting a file named `cluster.xml` on the (vert.x) classpath

Supporting the `hazelcast.config` system property configuration mechanism would be more flexible and aligns with instructions you'll find on the Hazelcast website.

**Comment by cescoffier** [comment]
PR merged.

**Comment by aschrijver** [comment]
Thanks!
