### ISSUE TITLE
HazelcastAsyncMap and HazelcastInternalAsyncMap should both rely on ConversionUtils

### ISSUE THREAD

**Issue by AshPlop** [vert-x3/vertx-hazelcast#61]
When adding elements in hazelcast map, values are wrapped whithin a `DataSerializableHolder,` but the two implementations use duplicated code to do so.

`HazelcastAsyncMap` has it's own private inner class (storing in the `HazelcastAsyncMap$DataSerializableHolder` objects as value)

`HazelcastInternalAsyncMap` uses the inner class declared in `ConversionUtils` (storing `ConversionUtils$DataSerializableHolder` objects as value).

`HazelcastAsyncMap` should be modified to use the Helper instead of using duplicated code, and it would be nice to change `ConversionUtils` from friendly visibility to public. When using Hazlecast `EntryProcessor` we need a way to read the values stored in the map, but with the current implementation the object is only available by using reflection to access the clusterSerializable property.

thanks

**Comment by tsegismont** [comment]
Sounds reasonable to me. Would you contribute it?

**Comment by AshPlop** [comment]
yes sure

**Comment by AshPlop** [comment]
Hi, here is the [PR (#68)](https://github.com/vert-x3/vertx-hazelcast/pull/68)

**Comment by tsegismont** [comment]
Closed via 76ab7fb
