### ISSUE TITLE
connecting to an existing hazelcast cluster in a rancher/docker network

### ISSUE THREAD

**Issue by fokoenecke** [vert-x3/vertx-hazelcast#81]
Hi there! We are using vertx (3.4.0) in following docker setup:

We have a cross-host rancher/docker network all our containers are deployed to. The core of our vertx communication is a hazelcast cluster of standalone hazelcast containers independent of vertx - apart from the map configuration from [here](http://vertx.io/docs/vertx-hazelcast/java/#_using_an_existing_hazelcast_cluster).

Our vertx service containers connect to this hazelcast cluster as [hazelcast clients](http://docs.hazelcast.org/docs/3.4/javadoc/com/hazelcast/client/HazelcastClient.html#newHazelcastClient(com.hazelcast.client.config.ClientConfig)). This works perfectly from inside the rancher network.

Now we would like to be able to connect to the cluster from outside the rancher network, e.g. to debug directly from the IDE. Therefore we opened the hazelcast port 5701 to access containers from outside the network via the hosts. When using plain hazelcast this works fine. Unfortunately it does not if we use the hazelcast instance in this vertx cluster manager.

After it says `HazelcastClient 3.8 is CLIENT_CONNECTED` sometimes nothing happens, sometimes the event loop thread gets blocked forever. The same code works when connecting to a hazelcast cluster in the same network as the client (e.g. localhost) It seems like vertx tries to use the internal IP of the rancher network to communicate to, instead of the external host IP.

It would be really kind if you had a hint if this could be a vertx issue. I can provide more information on this, if needed.

Greetings!

**Comment by tsegismont** [comment]
2017-08-10 20:32 GMT+02:00 fokoenecke <notifications@github.com>:

> Hi there! We are using vertx (3.4.0) in following docker setup:
>
> We have a cross-host rancher/docker network all our containers are
> deployed to. The core of our vertx communication is a hazelcast cluster of
> standalone hazelcast containers independent of vertx - apart from the map
> configuration from here
> <http://vertx.io/docs/vertx-hazelcast/java/#_using_an_existing_hazelcast_cluster>
> .
>

I don't understand your last statement. Are your Vert.x instances clustered
with Hazelcast? You can connect to a standalone Hazelcast cluster, that's
fine, but this cluster cannot be the Vert.x instances cluster.


> Our vertx service containers connect to this hazelcast cluster as hazelcast
> clients
> <http://docs.hazelcast.org/docs/3.4/javadoc/com/hazelcast/client/HazelcastClient.html#newHazelcastClient(com.hazelcast.client.config.ClientConfig)>.
> This works perfectly from inside the rancher network.
>
> Now we would like to be able to connect to the cluster from outside the
> rancher network, e.g. to debug directly from the IDE. Therefore we opened
> the hazelcast port 5701 to access containers from outside the network via
> the hosts. When using plain hazelcast this works fine. Unfortunately it
> does not if we use the hazelcast instance in this vertx cluster manager.
>
> After it says HazelcastClient 3.8 is CLIENT_CONNECTED sometimes nothing
> happens, sometimes the event loop thread gets blocked forever. The same
> code works when connecting to a hazelcast cluster in the same network as
> the client (e.g. localhost) It seems like vertx tries to use the internal
> IP of the rancher network to communicate to, instead of the external host
> IP.
>
> It would be really kind if you had a hint if this could be a vertx issue.
> I can provide more information on this, if needed.
>
> Greetings!
>

Smart clients are not supported. The Vert.x node must me a Hazelcast
cluster member.

**Comment by fokoenecke** [comment]
Thanks for your answer.
> Are your Vert.x instances clustered with Hazelcast?

Basically we are doing this:
```java
ClientConfig clientConfig = new ClientConfig(); // connecting to a node in the network
HazelcastInstance hazelcastInstance = HazelcastClient.newHazelcastClient(clientConfig);
ClusterManager mgr = new HazelcastClusterManager(hazelcastInstance);
VertxOptions options = new VertxOptions().setClusterManager(mgr);
Vertx.clusteredVertx(options, res -> {});
```
So our code does not create its own hazelcast node, but connecting as a client to an existing one. Is this not supported?

**Comment by tsegismont** [comment]
Yes, it's not supported.

2017-08-29 12:16 GMT+02:00 fokoenecke <notifications@github.com>:
