### ISSUE TITLE
microservice jar file size

### ISSUE THREAD

**Issue by MarWestermann** [vert-x3/vertx-hazelcast#83]
Hi,
I use vertx to create microservices running on openshift.
But now I figured out that if I include this modues as dependency my fat jars get a file size of > 50mb.
Is there a possibility to keep my jars small? IMHO having microservice jars that big is not the idea behind microservices?!

regards, Marco

**Comment by vietj** [comment]
can you list your actual dependencies with size ?

**Comment by vietj** [comment]
can we close this issue ?

**Comment by MarWestermann** [comment]
if you are ok with a file size > 26MB by default then yes

**Comment by vietj** [comment]
hum that seems to be an hazelcast issue

**Comment by vietj** [comment]
doesn't hazelcast provide a stripped down version ?

**Comment by vietj** [comment]
have you looked at the other cluster manager ?

**Comment by vbekiaris** [comment]
The Hazelcast distribution jar for the latest stable version (3.8.6) is ~8MB (http://search.maven.org/#artifactdetails%7Ccom.hazelcast%7Chazelcast%7C3.8.6%7Cjar). Which hazelcast artifacts are you including in your microservice fat-jar?

**Comment by tsegismont** [comment]
Hi @MarWestermann 

As @vbekiaris pointed out, the Vert.x Hazelcast cluster manager depends on a single Hazelcast JAR file. This JAR file is rather small considering the features brought in.

I'm not sure why you need Fabric8 Kubernetes API model and the rest, but it's definitely not an Hazelcast cluster manager issue.

**Comment by MarWestermann** [comment]
Hi @vbekiaris @tsegismont 
Hi don't directly include any hazelcast deps into my jar.. just the vertx-hazelcast:3.4.2 jar.

I just did another test:
create maven bundle by archetype: org.jetbrains.kotlin:kotlin-archetype-jvm:1.1.51
add the fabric8-vertx-plugin to build:

` 
           <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>vertx-maven-plugin</artifactId>
                <version>1.0.8</version>
                <executions>
                    <execution>
                        <id>vmp</id>
                        <goals>
                            <goal>initialize</goal>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <redeploy>true</redeploy>
                    <verticle>${main.verticle}</verticle>
                </configuration>
            </plugin>
`
Add vertx-core:3.4.2 as dependency

Package with mvn clean compile vertx:package
Result: 6,7 MB

Add vertx-hazelcast:3.4.2 dependency
package again
Result: 14 MB

Add vertx-config-kubernetes-configmap:3.4.2
package again
Result: 21,5 MB
