### ISSUE TITLE
cluster not work for me

### ISSUE THREAD

**Issue by Qinwroks** [vert-x3/vertx-hazelcast#9]
i am using java 8 with official vertx-samples.
```script
/Users/WB/Workspace/Vertx3/vertx-examples/core-examples/src/main/java/io/vertx/example/core/ha/Server.java
```

i run the Server.java in different cmd window, the cluster just not working.

so i write a test code like this:
```java
    public static void main(String[] args) {
       System.setProperty("vertx.cwd", "src/main/java/io/hale/core");
        Consumer<Vertx> runner = node -> {
            //.....
        };
       ClusterManager mgr = new HazelcastClusterManager();
        VertxOptions options = new VertxOptions()
                .setClustered(true)
                .setClusterManager(mgr);
        Vertx.clusteredVertx(options, res -> {
            if (res.succeeded()) {
                Vertx join = res.result();
                System.out.println("joined cluster node:" + join.toString());
                runner.accept(join);
            } else {
                throw new RuntimeException(res.cause());
            }
        });
}
```
and i started two of this, still not working.

THE TWO APPLICATIONS JUST NOT FOUND EACHOUTHER

**Comment by cescoffier** [comment]
So, it's more a problem of clustering than HA (HA exemple instructions are here: https://github.com/vert-x3/vertx-examples/tree/master/core-examples#high-availability).

Can you set the hazelcast logging to INFO so we get more information. By default it uses multicast, so maybe multicast is not working in your case, or you have several network interfaces and it does not pick the right one.

To set the log level to INFO, create a logging.properties file like this one: https://github.com/vert-x3/vertx-openshift-cartridge/blob/master/usr/shared/conf/logging.properties and add it to your classpath. Edit the `com.hazelcast.level=SEVERE` line to com.hazelcast.level=INFO`.

**Comment by purplefox** [comment]
Also, this might help:

http://vertx.io/docs/vertx-hazelcast/#_trouble_shooting_clustering

**Comment by Qinwroks** [comment]
OK, i am using MAC OS. i followed this page and solved my problem.
http://blogs.agilefaqs.com/2009/11/08/enabling-multicast-on-your-macos-unix/

**Comment by Qinwroks** [comment]
for this is not an vertx issue, i am close it.
