### ISSUE TITLE
"time-to-live-seconds" and "max-idle-seconds"  are not working as expected.

### ISSUE THREAD

**Issue by jinho-xthplanet** [vert-x3/vertx-hazelcast#96]
I am trying to use AsyncMap as cache. 
and I have set cluster.xml of hazelcast as below.

But, "time-to-live-seconds" and "max-idle-seconds"  are not working as expected.
AsyncMap datas are not evicted.

Do I need to add any code to use this function?

map configuartion in cluster.xml 
-------------------------------------------------------------------------------------------

<map name="__vertx.haInfo">

    
    <backup-count>0</backup-count>
    <async-backup-count>1</async-backup-count>
    
    <time-to-live-seconds>0</time-to-live-seconds>
    
    <max-idle-seconds>10</max-idle-seconds>
    
    <eviction-policy>NONE</eviction-policy>
    
    <max-size policy="PER_NODE">0</max-size>
    
    <eviction-percentage>25</eviction-percentage>
    
    <merge-policy>com.hazelcast.map.merge.LatestUpdateMapMergePolicy</merge-policy>

  </map>

**Comment by tsegismont** [comment]
Can you fix the xml snippet formatting? Besides it seems like an excerpt from the eventbus subscriptions multimap configuration.

**Comment by tsegismont** [comment]
Closing as I notice you sent two messages about this in the user forum. Please do not cross post the same problem.
